
version: '3'
services:
  terragrunt-engine-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: secret-token
    volumes:
      # Update path to allow tofu access from container to working directory
      - /projects:/projects
    ports:
      - "127.0.0.1:50051:50051"
